mkdir "Background models"
mkdir "Expected Groundwater Model"
mkdir "Figures"
mkdir "Iterations"
mkdir "Posterior PDFs"
copy log*.* "./Iterations"
copy model_bk*.* "./Background models"
copy model_wt_[0]*.* "./Expected Groundwater Model"
copy model_wt__1000.0_den*.* "./Posterior PDFs"
copy model_wt__1000.0_par*.* "./Posterior PDFs"
copy model_wt__1000.0_Zwt*.* "./Posterior PDFs"
copy model_wt__1000.0_hat*.* "./Expected Groundwater Model"
copy *.jpg "./Figures"

